baseURL: "https://devashishkhulbe.com"
languageCode: "en-us"
title: "Devashish Khulbe"

params:
  author: "Devashish Khulbe"
  email: "dk3596@nyu.edu"  # Replace with your actual email
  description: "Researcher and Ph.D. candidate specializing in Deep Learning"
  keywords: ["Deep Learning", "Graph Neural Networks"]
  
  # Social and academic links
  # github: "your-github-username"
  # linkedin: "your-linkedin-profile"
  scholar: "https://scholar.google.com/citations?user=jlDS4BwAAAAJ&hl=en"
  cv: "cv.pdf"  # Put your CV in static/ folder
  # orcid: "0000-0000-0000-0000"  # Optional
  # twitter: "your-twitter"  # Optional
  
  # Institution
  institution: "MUNI Digital City Lab"
  position: "Ph.D. Candidate"

menu:
  main:
    - name: "About"
      url: "/"
      weight: 1
    # - name: "Research"
    #   url: "#research"
      # weight: 2
    - name: "Publications"
      url: "#publications"
      weight: 2
    - name: "Teaching"
      url: "#teaching"
      weight: 3
    - name: "News"
      url: "#news"
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: false

# Disable unwanted Hugo features
disableKinds: ["taxonomy", "term", "RSS", "sitemap"]
